[[pages]]
path = "pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/data.py"
name = "Technology Project Data"
icon = "ğŸ“Š"
url_path = "data"

[[pages]]
path = "pages/mpt.py"
name = "Markowitz Portfolio Theory"
icon = "ğŸ“ˆ"
url_path = "mpt"

[[pages]]
path = "pages/drl.py"
name = "Deep Reinforcement Learning"
icon = "ğŸ¤–"
url_path = "drl"

[[pages]]
path = "pages/about.py"
name = "About"
icon = "â”"
url_path = "about"

[[pages]]
path = "pages/references.py"
name = "References"
icon = "ğŸ“š"
url_path = "references"